### ISSUE TITLE
YAGSL vendordep could declare required vendordeps

### ISSUE THREAD

**Issue by sciencewhiz** [BroncBotz3481/YAGSL-Lib#10]
Since 2024, vendordeps have been able to declare vendordeps that they require: https://github.com/wpilibsuite/native-utils/pull/163. YAGSL could do this to help with installation. The 2025 VS Code dependency manager will help automate this: https://github.com/wpilibsuite/vscode-wpilib/pull/715

**Comment by thenetworkgrinch** [comment]
I didnt know this existed! I will add that rn. I am holding off on publishing to the wpilib vendordep repo until all dependencies are updated to 2025

**Comment by thenetworkgrinch** [comment]
Just added it. Thanks!
